# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
ruby '~> 3.0.0'

gem "erubis"
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem 'webrick'
gem 'prettier'